# Generated by Django 2.2 on 2020-01-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('К', 'Комплекты ключей'), ('Ш', 'Поштучно')], default='K', max_length=1),
            preserve_default=False,
        ),
    ]
